language: node_js

sudo: required

addons:
  apt:
    packages:
     - lftp

os: linux

install:
  - 'nvm install node'
  - 'npm install npm'
  - 'npm install -g grunt-cli'
  - 'npm install'

script:
  - 'npm test'

deploy:
  - 'lftp -c "open -u $FTP_USER,$FTP_PASSWORD ftp.aledsz.com.br; set ssl:verify-certificate no; mirror -R -n ./src/ /hmditc/"'

notifications:
  - slack:
    rooms:
      - rarsystems:BSwsdqvNGJzwGurttLTDYGyF#projects
    on_success: always
    on_failure: always
