language: node_js

install:
  - 'nvm install node'
  - 'npm install npm'
  - 'npm install -g grunt-cli'
  - 'npm install'

script:
  - 'npm test'

after_success:
  - 'wput ./src/ ftp://$FTP_USER:$FTP_PASSWORD@aledsz.com.br/hmditc/'

notifications:
  - slack:
    rooms:
      - rarsystems:BSwsdqvNGJzwGurttLTDYGyF#projects
    on_success: always
    on_failure: always
