language: node_js

install:
  - 'nvm install node'
  - 'npm install npm'
  - 'npm install -g grunt-cli'
  - 'npm install'

script:
  - 'npm test'

after_success:
  - 'cd src/'
  - 'find ./ -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.aledsz.com.br/hmditc/{} \;'

notifications:
  slack: 
    rooms:
      - rarsystems:BSwsdqvNGJzwGurttLTDYGyF#projects
    on_success: always
    on_failure: always
