language: node_js

before script:
  - 'sudo npm install -g grunt-cli'

install:
  - 'npm install'

after script:
  - 'npm test'

notifications:
  - slack: rarsystems:BSwsdqvNGJzwGurttLTDYGyF#projects
