language: node_js
os: linux
sudo: require

install:
  - 'nvm install node'
  - 'npm install npm'
  - 'npm install -g grunt-cli'
  - 'npm install'

script:
  - 'npm test'

before_deploy:
  - 'sudo apt-get -qq update'
  - 'sudo apt-get install lftp'

deploy:
  - 'lftp -c "open -u $FTP_USER,$FTP_PASSWORD ftp.aledsz.com.br; set ssl:verify-certificate no; mirror -R -n ./src/ /hmditc/"'

notifications:
  slack: 
    rooms:
      - rarsystems:BSwsdqvNGJzwGurttLTDYGyF#projects
    on_success: always
    on_failure: always
